<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Render\Element;

/**
 * @file
 * Primary module hooks for DrupalEasy Repositories module.
 */

 /**
  * Implements hook_form_user_form_alter
  */
 function drupaleasy_repositories_form_user_form_alter(array &$form, FormStateInterface $form_state, string $form_id): void {
    foreach(Element::children($form['field_repository_url']['widget']) as $el_index) {
        $form['field_repository_url']['widget'][$el_index]['#process'][] = '_drupaleasy_repositories_url_help_text';
    }
 }

 function _drupaleasy_repositories_url_help_text(array $element, &$form_state, &$form) : array {
    return $element;
    
 }